# An example config file for running the sleep scripts
# All paths should be relative to this file

outdir = 'data/output/'
data_path = 'data/PIR_example_data.csv'
time_start = "2017-03-16 11:00:00"
time_end = "2017-03-23 11:00:00"
#
original_bin_size = 5
#
new_bin_size_mins = 1
# What minimally defines a sleep bout in seconds
sleep_period = 40
time_bin_for_mean_sleep_bout_calculation_mins = 30
columns_to_use = ['PIR1', 'PIR2', 'PIR3', 'PIR4', 'PIR5']
